### PR TITLE
Improve logging base address problems

### PR DESCRIPTION
**Pull request by Brett208**
Based on branch that updated location of OP2Internal source code

### CODE REVIEW

**Review by DanRStevens — APPROVED** [review]
I'm somewhat lukewarm about the last commit involving `MessageBox`. Mostly though I don't want to encourage use of `MessageBox`. It's a horrible hack, used by the lazy, when they can't find anything better. :wink: 

I'm wondering if the `LogWithModalDialog` method should be moved out of Log, and perhaps just placed in Main where it is used.

Small point, I'd suggest writing to the log file before presenting the modal dialog box, rather than after it.

No show stopping problems though.

**Comment by Brett208** [comment]
I'll move the function into main.

**Comment by Brett208** [comment]
If it looks good, please merge. 

Thanks,
Brett

**Comment by DanRStevens** [comment]
Ok, merging.

And yes, I fully admit I was the lazy programmer who used `MessageBox`.

**Pull request merged**
