### PR TITLE
Prevent Visual Studio from sorting header and .cpp files into separat…

### PR DESCRIPTION
**Pull request by Brett208**
…e filters

### CODE REVIEW

**Comment by Brett208** [comment]
I'm having trouble rebasing branches onto master.

**Comment by DanRStevens** [comment]
I was tempted to ask.

Looks like the other PR was set to merge to a non-master base branch. Then it was merged to the base branch after the base branch was already merged to master.

Probably could have edited the PR to merge to master rather than rebasing the branch.

At any rate, looks like it's all solved now.

**Comment by Brett208** [comment]
I merged the base branch onto master. Then on my machine I force rebased this branch (well the branch this one replaced) onto the current master. After pushing the force rebase to github, I tried merging from github. I don't understand why the force rebase on my machine and pushing didn't seem to change which branch the github pull request was based on. I must be missing something in understanding the process.

**Comment by DanRStevens** [comment]
Yeah, the merge destination and the base branch for a git rebase are separate concepts.

Editing the PR (title and mergeDestination) are like changing the first line:
```
git checkout mergeDestination  # Typically mergeDestination = master
git merge mergeTarget  # Typically the PR branch
```

Doing a Git rebase, is about rewriting the history of a branch. Not too sure how to illustrate that with text. In this case, it would rewrite branch2, so it would branch off the merge commit for branch1, and filter out the commits from branch1.

Instead, if both branches were merged directly to master, the merge commit for branch1 would show parents for the current master (which might still be the common branch point) and the commits for branch1. The merge commit for branch2 would show parents for the current master (which would now contain the merge commit for branch1) and the commits for both branch1 and branch2.

Post merge of two branches directly to master (note the non-linear history):
```
commonPoint -> commitOn1 -> merge1 -> merge2 (master)
           \-> commitOn1 -> commitOn2 -/
```

**Pull request merged**
